### ISSUE TITLE
Add support for emacs

### ISSUE THREAD

**Issue by M1ndo** [momaek/formattag#11]
I'm not sure if there's a package for Emacs that's does something similar to this.
UPDATE: I have not found a package that has can do this so i'll create my own and share it here.

**Comment by M1ndo** [comment]
I've created an Emacs [package](https://github.com/M1ndo/gofmt-tag) for formattag if you'd like to also add it in the README.

**Comment by momaek** [comment]
https://github.com/momaek/formattag#emacs

**Comment by M1ndo** [comment]
Thanks!
