### ISSUE TITLE
v0.0.9 does not work as an External Tool on GoLand 

### ISSUE THREAD

**Issue by varfrog** [momaek/formattag#14]
Version v0.0.8 worked fine but the v0.0.9 just hangs. Here's the config

![image](https://github.com/momaek/formattag/assets/16167390/a631218f-dacb-43ba-9311-6f48d784c922)

Running formattag as an external tool, it hangs like this:

![image](https://github.com/momaek/formattag/assets/16167390/50bea4f1-3edf-40ad-acda-824103ca30a4)

Whereas if I run the very same command on the command line, it works fine. Any ideas? And again, the previous version works perfectly.

**Comment by momaek** [comment]
@Lewinz

**Comment by miclle** [comment]
https://github.com/momaek/formattag/pull/16

**Comment by varfrog** [comment]
Thank you @miclle ! This fixes it.
