### ISSUE TITLE
Add generics support

### ISSUE THREAD

**Issue by egorlepa** [momaek/formattag#3]
```
./migration/migration.go:285:14: expected '(', found '['
```

**Comment by momaek** [comment]
fixed, Please check the latest version

**Comment by egorlepa** [comment]
```
go get github.com/momaek/formattag@v0.0.7
for var in $(find . -type f -name "*.go"); do formattag -file $var ; done
```
still getting erorrs
```
 expected '(', found '[' (and 1 more errors)
```
```
func contains[T string](s []T, e T) bool {
	for i := range s {
		if s[i] == e {
			return true
		}
	}
	return false
}
```

or maybe i am updating it wrong?

**Comment by momaek** [comment]
Emmm.. Can you check the binay download from release page ?
https://github.com/momaek/formattag/releases/tag/v0.0.7

**Comment by egorlepa** [comment]
ok it works, thank you
also update readme pls:
i guess it requires go 1.18 now
and command should be 
```
go install github.com/momaek/formattag@v0.0.7
```
installing executables with 'go get' in module mode is deprecated.

**Comment by momaek** [comment]
OK. Updated
