### ISSUE TITLE
Support for stdin input?

### ISSUE THREAD

**Issue by ravsii** [momaek/formattag#8]
Hello. Is it possible to include support for stdin input, instead of specifying a filepath? So that `cat file.go | formattag --stdin` (or something) would format tags and output results it to `stdout`.

Some context: I've recently moved from VSCode to Helix. It's still in the development and there's no support for something like `${FILE}` variable, like in vscode, but it does support unix `|` pipe as a first class operator/function, so that piping into other commands (like `sort`) is very easy.

I probably can do a PR, but it could me take a while to get familiar with the codebase.

**Comment by momaek** [comment]
Now support stdin input.  plz check the latest version
